In [1]:
!pip install xgboost

Requirement already satisfied: xgboost in /usr/local/lib/python3.12/dist-packages (3.2.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.0.2)
Requirement already satisfied: nvidia-nccl-cu12 in /usr/local/lib/python3.12/dist-packages (from xgboost) (2.29.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from xgboost) (1.16.3)

In [2]:
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import StackingClassifier

In [3]:
iris = load_iris()

X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [4]:
classifiers = {
    "LogisticRegression": LogisticRegression(max_iter=200),
    "SVM": SVC(),
    "DecisionTree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(),
    "NaiveBayes": GaussianNB(),
    "RandomForest": RandomForestClassifier(),
    "GradientBoosting": GradientBoostingClassifier(),
    "AdaBoost": AdaBoostClassifier()
}

In [5]:
results = []

for name, model in classifiers.items():

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred, average="weighted")
    rec = recall_score(y_test, y_pred, average="weighted")
    f1 = f1_score(y_test, y_pred, average="weighted")

    results.append([name, acc, prec, rec, f1])

In [6]:
results_df = pd.DataFrame(
    results,
    columns=["Classifier", "Accuracy", "Precision", "Recall", "F1 Score"]
)

results_df.sort_values(by="Accuracy", ascending=False)

           Classifier  Accuracy  Precision    Recall  F1 Score
0  LogisticRegression  1.000000   1.000000  1.000000  1.000000
1                 SVM  1.000000   1.000000  1.000000  1.000000
2        DecisionTree  1.000000   1.000000  1.000000  1.000000
3                 KNN  1.000000   1.000000  1.000000  1.000000
4          NaiveBayes  1.000000   1.000000  1.000000  1.000000
5        RandomForest  1.000000   1.000000  1.000000  1.000000
6    GradientBoosting  1.000000   1.000000  1.000000  1.000000
7            AdaBoost  0.933333   0.933333  0.933333  0.933333

In [7]:
top4 = results_df.sort_values(by="Accuracy", ascending=False).head(4)

top4

           Classifier  Accuracy  Precision  Recall  F1 Score
0  LogisticRegression       1.0        1.0     1.0       1.0
1                 SVM       1.0        1.0     1.0       1.0
2        DecisionTree       1.0        1.0     1.0       1.0
3                 KNN       1.0        1.0     1.0       1.0

In [8]:
model1 = RandomForestClassifier()
model2 = SVC(probability=True)
model3 = KNeighborsClassifier()
model4 = DecisionTreeClassifier()

In [9]:
model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)
model4.fit(X_train,y_train)

DecisionTreeClassifier()

In [10]:
bagging = BaggingClassifier(
    estimator=model4,
    n_estimators=10,
    random_state=42
)

bagging.fit(X_train,y_train)

y_pred = bagging.predict(X_test)

print("Bagging Accuracy:", accuracy_score(y_test,y_pred))

Bagging Accuracy: 1.0

In [11]:
boosting = AdaBoostClassifier(
    estimator=model4,
    n_estimators=50
)

boosting.fit(X_train,y_train)

y_pred = boosting.predict(X_test)

print("Boosting Accuracy:", accuracy_score(y_test,y_pred))

Boosting Accuracy: 1.0

In [12]:
estimators = [
    ("rf", model1),
    ("svm", model2),
    ("knn", model3),
    ("dt", model4)
]

stack = StackingClassifier(
    estimators=estimators,
    final_estimator=LogisticRegression()
)

stack.fit(X_train,y_train)

y_pred = stack.predict(X_test)

print("Stacking Accuracy:", accuracy_score(y_test,y_pred))

Stacking Accuracy: 1.0